"""once again gg gg

Revision ID: 7ab95fa5efd0
Revises: cedca10a6814
Create Date: 2024-09-17 09:21:27.214120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ab95fa5efd0'
down_revision: Union[str, None] = 'cedca10a6814'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('employee_leave_issuer_leave_issuer_id_fkey', 'employee_leave_issuer', schema='dbo', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('employee_leave_issuer_leave_issuer_id_fkey', 'employee_leave_issuer', 'leave_issuer', ['leave_issuer_id'], ['leave_issuer_id'], source_schema='dbo', referent_schema='dbo')
    # ### end Alembic commands ###
