"""once again gg

Revision ID: cedca10a6814
Revises: 
Create Date: 2024-09-17 09:04:22.013636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cedca10a6814'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE SCHEMA  IF NOT EXISTS raw;')
    op.execute('CREATE SCHEMA  IF NOT EXISTS dbo;')
    op.create_table('allocations',
    sa.Column('allocation_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('allocation_id'),
    schema='dbo'
    )
    op.create_table('departments',
    sa.Column('department_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('department_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('department_id'),
    sa.UniqueConstraint('department_name'),
    schema='dbo'
    )
    op.create_table('designations',
    sa.Column('designation_id', sa.Integer(), nullable=False),
    sa.Column('designation_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('designation_id'),
    schema='dbo'
    )
    op.create_table('fiscal_year',
    sa.Column('fiscal_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('fiscal_id'),
    schema='dbo'
    )
    op.create_table('imported_leave_information',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('empId', sa.String(length=255), nullable=False),
    sa.Column('teamManagerId', sa.Integer(), nullable=True),
    sa.Column('designationId', sa.Integer(), nullable=False),
    sa.Column('designationName', sa.String(length=255), nullable=False),
    sa.Column('firstName', sa.String(length=255), nullable=False),
    sa.Column('middleName', sa.String(), nullable=True),
    sa.Column('lastName', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('isHr', sa.Boolean(), nullable=False),
    sa.Column('isSupervisor', sa.Boolean(), nullable=False),
    sa.Column('leaveIssuerId', sa.Integer(), nullable=True),
    sa.Column('issuerFirstName', sa.String(length=255), nullable=True),
    sa.Column('issuerMiddleName', sa.String(), nullable=True),
    sa.Column('issuerLastName', sa.String(length=255), nullable=True),
    sa.Column('currentLeaveIssuerId', sa.Integer(), nullable=True),
    sa.Column('currentLeaveIssuerEmail', sa.String(length=255), nullable=True),
    sa.Column('departmentDescription', sa.Text(), nullable=False),
    sa.Column('startDate', sa.Date(), nullable=False),
    sa.Column('endDate', sa.Date(), nullable=False),
    sa.Column('leaveDays', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('leaveStatus', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('responseRemarks', sa.Text(), nullable=True),
    sa.Column('leaveTypeId', sa.Integer(), nullable=False),
    sa.Column('leaveType', sa.String(length=255), nullable=False),
    sa.Column('defaultDays', sa.Integer(), nullable=False),
    sa.Column('transferableDays', sa.Integer(), nullable=False),
    sa.Column('isConsecutive', sa.Integer(), nullable=False),
    sa.Column('fiscalId', sa.Integer(), nullable=False),
    sa.Column('fiscalStartDate', sa.DateTime(), nullable=False),
    sa.Column('fiscalEndDate', sa.DateTime(), nullable=False),
    sa.Column('fiscalIsCurrent', sa.Boolean(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.Column('isAutomated', sa.Integer(), nullable=False),
    sa.Column('isConverted', sa.Integer(), nullable=False),
    sa.Column('totalCount', sa.Integer(), nullable=False),
    sa.Column('allocations', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='dbo'
    )
    op.create_table('leave_issuer',
    sa.Column('leave_issuer_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('leave_issuer_id'),
    schema='dbo'
    )
    op.create_table('leave_types',
    sa.Column('leave_type_id', sa.Integer(), nullable=False),
    sa.Column('leave_type', sa.String(length=100), nullable=False),
    sa.Column('default_days', sa.Integer(), nullable=False),
    sa.Column('transferrable_days', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('leave_type_id'),
    schema='dbo'
    )
    op.create_table('team_managers',
    sa.Column('team_manager_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('team_manager_id'),
    schema='dbo'
    )
    op.create_table('imported_leave_information',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('empId', sa.String(), nullable=True),
    sa.Column('teamManagerId', sa.Integer(), nullable=True),
    sa.Column('designationId', sa.Integer(), nullable=True),
    sa.Column('designationName', sa.String(), nullable=True),
    sa.Column('firstName', sa.String(), nullable=True),
    sa.Column('middleName', sa.String(), nullable=True),
    sa.Column('lastName', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('isHr', sa.Boolean(), nullable=True),
    sa.Column('isSupervisor', sa.Boolean(), nullable=True),
    sa.Column('leaveIssuerId', sa.Integer(), nullable=True),
    sa.Column('issuerFirstName', sa.String(), nullable=True),
    sa.Column('issuerMiddleName', sa.String(), nullable=True),
    sa.Column('issuerLastName', sa.String(), nullable=True),
    sa.Column('currentLeaveIssuerId', sa.Integer(), nullable=True),
    sa.Column('currentLeaveIssuerEmail', sa.String(), nullable=True),
    sa.Column('departmentDescription', sa.Text(), nullable=True),
    sa.Column('startDate', sa.Date(), nullable=True),
    sa.Column('endDate', sa.Date(), nullable=True),
    sa.Column('leaveDays', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('leaveStatus', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('responseRemarks', sa.Text(), nullable=True),
    sa.Column('leaveTypeId', sa.Integer(), nullable=True),
    sa.Column('leaveType', sa.String(), nullable=True),
    sa.Column('defaultDays', sa.Integer(), nullable=True),
    sa.Column('transferableDays', sa.Integer(), nullable=True),
    sa.Column('isConsecutive', sa.Integer(), nullable=True),
    sa.Column('fiscalId', sa.Integer(), nullable=True),
    sa.Column('fiscalStartDate', sa.DateTime(), nullable=True),
    sa.Column('fiscalEndDate', sa.DateTime(), nullable=True),
    sa.Column('fiscalIsCurrent', sa.Boolean(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.Column('isAutomated', sa.Integer(), nullable=True),
    sa.Column('isConverted', sa.Integer(), nullable=True),
    sa.Column('totalCount', sa.Integer(), nullable=True),
    sa.Column('allocations', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='raw'
    )
    op.create_table('employees',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('is_hr', sa.Boolean(), nullable=False),
    sa.Column('is_supervisor', sa.Boolean(), nullable=False),
    sa.Column('designation_id', sa.Integer(), nullable=False),
    sa.Column('team_manager_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['dbo.departments.department_id'], ),
    sa.ForeignKeyConstraint(['designation_id'], ['dbo.designations.designation_id'], ),
    sa.PrimaryKeyConstraint('employee_id'),
    schema='dbo'
    )
    op.create_table('employee_allocations',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('allocation_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['allocation_id'], ['dbo.allocations.allocation_id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['dbo.employees.employee_id'], ),
    sa.PrimaryKeyConstraint('employee_id', 'allocation_id'),
    schema='dbo'
    )
    op.create_table('employee_leave_issuer',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('leave_issuer_id', sa.Integer(), nullable=False),
    sa.Column('is_current_leave_issuer', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['dbo.employees.employee_id'], ),
    sa.ForeignKeyConstraint(['leave_issuer_id'], ['dbo.leave_issuer.leave_issuer_id'], ),
    sa.PrimaryKeyConstraint('employee_id', 'leave_issuer_id'),
    schema='dbo'
    )
    op.create_table('employee_leaves',
    sa.Column('leave_id', sa.Integer(), nullable=False),
    sa.Column('leave_issuer_id', sa.Integer(), nullable=False),
    sa.Column('leave_type_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_id', sa.Integer(), nullable=False),
    sa.Column('leave_days', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('is_consecutive', sa.Boolean(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['dbo.employees.employee_id'], ),
    sa.ForeignKeyConstraint(['fiscal_id'], ['dbo.fiscal_year.fiscal_id'], ),
    sa.ForeignKeyConstraint(['leave_type_id'], ['dbo.leave_types.leave_type_id'], ),
    sa.PrimaryKeyConstraint('leave_id'),
    schema='dbo'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee_leaves', schema='dbo')
    op.drop_table('employee_leave_issuer', schema='dbo')
    op.drop_table('employee_allocations', schema='dbo')
    op.drop_table('employees', schema='dbo')
    op.drop_table('imported_leave_information', schema='raw')
    op.drop_table('team_managers', schema='dbo')
    op.drop_table('leave_types', schema='dbo')
    op.drop_table('leave_issuer', schema='dbo')
    op.drop_table('imported_leave_information', schema='dbo')
    op.drop_table('fiscal_year', schema='dbo')
    op.drop_table('designations', schema='dbo')
    op.drop_table('departments', schema='dbo')
    op.drop_table('allocations', schema='dbo')
    # ### end Alembic commands ###
