"""once again gg gg

Revision ID: f1f2d7251757
Revises: 7ab95fa5efd0
Create Date: 2024-09-17 09:22:31.226774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1f2d7251757'
down_revision: Union[str, None] = '7ab95fa5efd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee_leave_issuer', 'leave_issuer_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               schema='dbo')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee_leave_issuer', 'leave_issuer_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               schema='dbo')
    # ### end Alembic commands ###
