insert into dbo.imported_leave_information(
SELECT 
id, 
"userId", 
"empId", 
"teamManagerId", 
"designationId", 
"designationName", 
"firstName", 
"middleName", 
"lastName", 
email, 
"isHr", 
"isSupervisor", 
"leaveIssuerId", 
"issuerFirstName", 
"issuerMiddleName", 
"issuerLastName", 
"currentLeaveIssuerId", 
"currentLeaveIssuerEmail", 
"departmentDescription", 
"startDate", 
"endDate", 
"leaveDays", 
reason, 
"leaveStatus", 
status, 
"responseRemarks", 
"leaveTypeId", 
"leaveType", 
"defaultDays", 
"transferableDays", 
"isConsecutive", 
"fiscalId", 
"fiscalStartDate", 
"fiscalEndDate", 
"fiscalIsCurrent", 
"createdAt", 
"updatedAt", 
"isAutomated", 
"isConverted", 
"totalCount", 
NULLIF(allocations::TEXT, 'null')::JSONB AS allocations
FROM raw.imported_leave_information
)
on conflict (id)
do nothing;
